name: robo-backup
recipe: lamp
config:
  webroot: web

services:
  pma:
    type: phpmyadmin
    hosts:
      - database

proxy:
  pma:
    - robo-backup-db.lndo.site

tooling:
  which:
    service: appserver
    cmd: which

  robo:
    service: appserver
    cmd: robo

  wp:
    service: appserver
    cmd: wp